version: "3"

services:
    db:
        image: postgres:latest
        container_name: postgres-db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 05071984
            POSTGRES_DB: contacts_app
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:latest
        container_name: redis-cache
        restart: always
        ports:
            - "6379:6379"

    app:
        build: .
        container_name: fastapi-app
        restart: always
        depends_on:
            - db
            - redis
        environment:
            DATABASE_URL: postgresql+asyncpg://postgres:05071984@db:5432/contacts_app
            REDIS_URL: redis://redis:6379/0
        ports:
            - "8000:8000"
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
    pgdata:
