"""Add refresh token

Revision ID: 3a0de2e5dd80
Revises: c108846025e9
Create Date: 2025-02-18 23:43:06.321531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0de2e5dd80'
down_revision: Union[str, None] = 'c108846025e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'refresh_token')
    # ### end Alembic commands ###
